 Machine Learning - Assignment1. 
Zohreh Ghasemi                                       20 January 2023

In [166]:
import os
import sys
import warnings

import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from mizani.formatters import percent_format
from plotnine import *
from stargazer import stargazer
from statsmodels.tools.eval_measures import mse, rmse
warnings.filterwarnings("ignore")
# turning off scientific notation

In [ ]:
df= pd.read_csv("morg2014.csv" , header = 0, sep =',')

In [183]:
df["female"] = (df["sex"] == 2)
df["w"] = df["earnwke"] / df["uhourse"]
df["agesq"] = np.power(df["age"], 2)
df["agecu"] = np.power(df["age"], 3)
df["agequ"] = np.power(df["age"], 4)

In [184]:
# data summary
df.describe()

,hhid,hurespli,hrsample,hrhhid2,serial,hhnum,cbsafips,county,centcity,smsastat,...,ch02,ch35,ch613,ch1417,ch05,ihigrdc,w,agesq,agecu,agequ
count,4.335000e+03,4335.000000,4335.000000,4335.000000,4335.000000,4335.000000,4335.000000,4335.000000,3488.000000,4285.000000,...,4335.000000,4335.000000,4335.000000,4335.000000,4335.000000,4335.000000,3758.0000,4335.000000,4335.000000,4.335000e+03
mean,4.587748e+14,1.359631,7089.367243,70894.717878,1.047751,1.045444,24399.204152,27.039216,2.008601,1.209802,...,0.044060,0.061130,0.163552,0.133333,0.090657,13.883852,inf,2389.389158,129052.344175,7.300593e+06
std,3.211526e+14,0.702086,3798.645153,37986.465506,0.268787,0.222234,20508.050916,66.293963,0.712006,0.407214,...,0.205252,0.239597,0.369912,0.339974,0.287154,2.007385,NaN,1261.657460,96639.000224,7.100886e+06
min,4.314912e+10,0.000000,101.000000,1011.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,256.000000,4096.000000,6.553600e+04
25%,1.482955e+14,1.000000,9100.000000,91001.000000,1.000000,1.000000,0.000000,0.000000,2.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,12.5000,1296.000000,46656.000000,1.679616e+06
50%,4.408099e+14,1.000000,9200.000000,92001.000000,1.000000,1.000000,26180.000000,0.000000,2.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,16.5000,2401.000000,117649.000000,5.764801e+06
75%,7.363525e+14,2.000000,9200.000000,92001.000000,1.000000,1.000000,38020.000000,33.000000,3.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,16.000000,21.6345,3249.000000,185193.000000,1.055600e+07
max,9.998704e+14,9.000000,9300.000000,93002.000000,11.000000,3.000000,79600.000000,810.000000,3.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,18.000000,inf,7225.000000,614125.000000,5.220062e+07

In [170]:
# select occupation
df = df[df["occ2012"]==5700]

In [181]:
df.head(5)

,hhid,intmonth,hurespli,minsamp,hrlonglk,hrsample,hrhhid2,serial,hhnum,state,...,ch1417,ch05,ihigrdc,docc00,dind02,female,w,agesq,agecu,agequ
104,210312097001502,January,1.0,MIS 4,MIS 2-4 Or MIS 6-8 (link To,9200,92001,1,1,63,...,0,0,18.0,Office and administrative support occupations,Educational services,True,4.6152,841,24389,707281
120,431091309100666,January,1.0,MIS 8,MIS 2-4 Or MIS 6-8 (link To,9100,91002,2,2,63,...,0,0,12.0,Office and administrative support occupations,Construction,True,9.2500,625,15625,390625
160,27690310999096,January,2.0,MIS 8,MIS 2-4 Or MIS 6-8 (link To,9100,91001,1,1,63,...,0,0,12.0,Office and administrative support occupations,Construction,True,9.0000,3249,185193,10556001
275,959051987039820,January,1.0,MIS 8,MIS 2-4 Or MIS 6-8 (link To,9100,91001,1,1,63,...,0,0,15.0,Office and administrative support occupations,Wood products,True,8.5000,961,29791,923521
337,420869033909068,January,2.0,MIS 8,MIS 2-4 Or MIS 6-8 (link To,9100,91001,1,1,94,...,0,0,12.0,Office and administrative support occupations,Utilities,True,25.0000,3249,185193,10556001

In [182]:
#check missing variable in our data
df.isnull().sum()

hhid          0
intmonth      0
hurespli      0
minsamp       0
hrlonglk      0
           ...
female        0
w           577
agesq         0
agecu         0
agequ         0
Length: 101, dtype: int64

In [173]:
# Linear regressions

# Model 1: Linear regression
model1 = "w ~ female + age"

# Models 2-5: Multiple linear regressions

model2 = "w ~ female + age + female*age + agesq + race + prcitshp "
model3 = "w ~ female + age + female*age + agesq + race + prcitshp + ownchild + marital + grade92 + female*grade92"
model4 = "w ~ female + age + female*age + agesq + race + prcitshp + ownchild + marital + grade92 + female*grade92 + agecu + agequ + female*agecu + female*agequ"


model_equations = [model1, model2, model3, model4]

In [185]:
regs = []
for equation in model_equations:
   regs.append(smf.ols(equation, df).fit(cov_type="HC1"))

In [186]:
regs[0].summary()

ValueError: r_matrix performs f_test for using dimensions that are asymptotically non-normal

In [187]:
# BIC of models in the full sample
BICs = []
for reg in regs:
    BICs.append(reg.bic)
BICs = [float('{:.3f}'.format(i)) for i in BICs]
BICs

[nan, nan, nan, nan]

In [188]:
# RMSE of models in the full sample
w_real = df["w"].values.tolist()
RMSEs = []
for reg in regs:
    w_pred = reg.predict()
    RMSEs.append(rmse(w_real, w_pred))
RMSEs = [float('{:.3f}'.format(i)) for i in RMSEs]
RMSEs

ValueError: operands could not be broadcast together with shapes (4335,) (3758,)

In [ ]:
results = pd.Series("model_equations")
results["BICs"] = BICs
results["RMSEs"] = RMSEs
results

In [ ]:
# import math
# from sklearn.metrics import mean_squared_error
# w_real = df["w"].values.tolist()
# RMSE1 = []
# for reg in regs:
#     w_pred = reg.predict()
#     MSE = mean_squared_error(w_real, w_pred)
#     RMSE1.append(math.sqrt(MSE))
# RMSE1

In [189]:
import statsmodels.formula.api as smf
from sklearn.model_selection import KFold
from statsmodels.tools.eval_measures import rmse


def ols_crossvalidator(formula: str, data: pd.DataFrame, n_folds=5, average_rmse=True):


    # Get dependent variable

    y = formula.split("~")[0].strip()

    # Get statistics on the whole work data

    model = smf.ols(formula, data=data).fit()

    rsquared = model.rsquared
    # n_coefficients = model.params.shape[0]
    n_coefficients = (
        model.df_model + 1
    )  # This might differ from model.params.shape[0], because of collinear predictors
    bic = model.bic
    rmse_alldata = rmse(model.predict(), data[y])

    # Calculating test and train RMSE-s for each fold

    k = KFold(n_splits=n_folds, shuffle=False, random_state=None)

    rmse_train = []
    rmse_test = []

    for train_index, test_index in k.split(data):

        data_train, data_test = data.iloc[train_index, :], data.iloc[test_index, :]

        model = smf.ols(formula, data=data_train).fit()

        rmse_train.append(rmse(data_train[y], model.predict(data_train)))
        rmse_test.append(rmse(data_test[y], model.predict(data_test)))

    if average_rmse:
        rmse_train = np.mean(rmse_train)
        rmse_test = np.mean(rmse_test)

    return {
        "RMSE": rmse_alldata,
        "R-squared": rsquared,
        "BIC": bic,
        "Coefficients": n_coefficients,
        "Training RMSE": rmse_train,
        "Test RMSE": rmse_test,
    }

In [ ]:
n_fold = 4

In [ ]:
cv_list = []
for equation in model_equations:
    cv_list.append(ols_crossvalidator(equation, df, n_fold, average_rmse=False))

In [ ]:
(
    pd.DataFrame(cv_list)
    .round(3)
    .assign(
        RMSE=lambda x: x["RMSE"],
        BIC=lambda x: x["BIC"].astype(int),
        Coefficients=lambda x: x["Coefficients"].astype(int),
        Model=["Model " + str(i + 1) for i in range(len(model_equations))],
    )
    .filter(["Model", "Coefficients", "R-squared", "RMSE", "BIC"])
    .set_index("Model")
)

In [ ]:
pd.DataFrame(
    [cv["Test RMSE"] for cv in cv_list],
    index=["Model " + str(i + 1) for i in range(len(cv_list))],
    columns=["Fold" + str(i + 1) for i in range(len(cv_list[0]["Test RMSE"]))],
).assign(Average=lambda x: x.mean(axis=1)).T